# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovialQuiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovialQuiz
  pod 'SnapKit', '~> 4.0.0'
  pod 'SVProgressHUD'
  
  #  pod 'Alamofire'
  pod 'Alamofire-Gloss'
  pod 'Gloss', '~> 2.0'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  # Facebook
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end
